#!/usr/bin/perl -p
# Eleet filter, Copyright 1999 by Joey Hess under the terms of the GNU GPL.
BEGIN {
	$transstring="4bcd3fgh1jklmn0pqr5+uvwxyz";
	$t="tr/a-zA-Z/$transstring".uc($transstring)."/";
}
eval $t;
s:h:|-|:ig;
s:l:|_:ig;
s:m:/\\/\\:ig;
s:n:/\\/:ig;
s:v:\\/:ig;
s:x:><:ig;
