.TH FILTERS 6
.SH NAME
ken, b1ff, chef, cockney, eleet, jethro, jibberish, jive, kraut, nyc, rasterman, upside-down \- assorted text filters
.SH SYNOPSIS
 $SHELL | chef
.SH "DESCRIPTION"
All of these programs are filters to do all sorts of strange things to text.
No racial or societal slurs are intended. For amusement only.
.P
All the filters read input from stdin, change it, and write the filtered
text to stdout.
.IP b1ff
The B1FF filter
.IP cockney
Cockney English
.IP chef
convert English on stdin to Mock Swedish on stdout
.IP eleet
K3wl hacker slang
.IP jethro
Hillbilly text filter
.IP jive
Jive English
.IP jibberish
Runs text through all the rest of the filters, to make really weird output.
.IP ken
English into Cockney, featuring (dubious) rhyming
slang for a lot of computer terminology.
.IP kraut
Generates text with a German accent.
.IP nyc
Brooklyn English
.IP rasterman
Makes text look like it came from the keyboard of Carsten Haitzler.
.IP upside-down
Flips text upside down. Stand on your head and squint to read the output.
.SH "SEE ALSO"
.IP /usr/share/doc/filters/SAMPLES
Lists samples of the output of all the filters.
.SH AUTHOR
The eleet, upside-down, chef, and b1ff filters were written by Joey
Hess <joey@kitenet.net>. Daniel V Klein <dvk@lonewolf.com> wrote the
cockney, jive, and nyc filters. jibberish is by Raul Miller
<rdm@test.legislate.com>, jethro is by Duane Paulson
<ci922@cleveland.freenet.edu>, rasterman is by Zachary Beane, ken is by
Stephen K Mulrine <skm@eqsn.net> and kraut is by John Sparks.
