.TH FILTERS 6
.SH NAME
b1ff, eleet, chef, jethro, jibberish, kraut, upside-down \- assorted text filters
.SH SYNOPSIS
All the filters read input from stdin, change it, and write the filtered
text to stdout.
.SH "DESCRIPTION"
All of these programs are filters to do all sorts of strange things to text.
No racial or societal slurs are intended. For amusement only.
.IP b1ff
The B1FF filter
.IP chef
convert English on stdin to Mock Swedish on stdout
.IP jethro
Hillbilly text filter
.IP jibberish
Runs text through all the rest of the filters, to make really weird output.
.IP eleet
K3wl hacker slang
.IP kraut
Generates text with a German accent.
.IP upside-down
Flips text upside down. Stand on your head and squint to read the output.
.SH "SEE ALSO"
.IP /usr/share/doc/filters/SAMPLES
Lists samples of the output of all the filters.
.SH AUTHOR
The filters were written by Joey Hess <joey@kitenet.net>, except jibberish,
which is by Raul Miller <rdm@test.legislate.com>.
