.TH FILTERS 6
.SH NAME
aust, b1ff, biffa, buck, censor, chef, cockney, drawl, fin, fudd, jethro jive ken, kraut, ky00te, mb, moo, newspeak, nyc, valspeak \- assorted text filters
.SH SYNOPSIS
All the filters read input from stdin, change it, and write the filtered
text to stdout.
.SH "DESCRIPTION"
All of these programs are filters to do all sorts of strange things to text.
No racial or societal slurs are intended. For amusement only.
.IP aust
Australian
.IP b1ff
The B1FF filter
.IP biffa
??
.IP buck
The buckwheat filter
.IP censor
[CENSORED]
.IP chef
convert English on stdin to Mock Swedish on stdout
.IP cockney
Cockney English
.IP drawl
English to Texan translator
.IP fin
??
.IP fudd
Elmer Fudd
.IP jethro
Hillbilly text filter
.IP jive
Jive English
.IP ken
English into Cockney, featuring (dubious) rhyming
slang for a lot of computer terminology.
.IP kraut
German
.IP mb
Marc Barrett posting translator
.IP moo
The cow filter
.IP newspeak
As in 1984
.IP nyc
Brooklyn English
.IP valspeak
??
.IP ky00te
This program places a very cute (and familiar to FurryMuck
fans) accent to any text file.
.SH "SEE ALSO"
.IP /usr/doc/filters/SAMPLES
Lists samples of the output of all the filters.
.SH AUTHOR
The filters were collected from all over, by Joey Hess <joey@kite.ml.org>
