module.exports = {
  b1ff: require('./src/b1ff')['b1ff'],
  censor: require('./src/censor')['censor'],
  chef: require('./src/chef')['chef'],
  cockney: require('./src/cockney')['cockney'],
  eleet: require('./src/eleet')['eleet'],
  fudd: require('./src/fudd')['fudd'],
  jethro: require('./src/jethro')['jethro'],
  ken: require('./src/ken')['ken'],
  kenny: require('./src/kenny')['kenny'],
  ky00te: require('./src/ky00te')['ky00te'],
  klaus: require('./src/klaus')['klaus'],
  LOLCAT: require('./src/LOLCAT')['LOLCAT'],
  nethackify: require('./src/nethackify')['nethackify'],
  newspeak: require('./src/newspeak')['newspeak'],
  nyc: require('./src/nyc')['nyc'],
  pirate: require('./src/pirate')['pirate'],
  rasterman: require('./src/rasterman')['rasterman'],
  scottish: require('./src/scottish')['scottish'],
  scramble: require('./src/scramble')['scramble'],
  spammer: require('./src/spammer')['spammer'],
  studly: require('./src/studly')['studly'],
  uniencode: require('./src/uniencode')['uniencode'],
  upside_down: require('./src/upside_down')['upside_down'],
};
